syntax = "proto3";

package product.v1;
option go_package = "gen/product/v1;productv1";

service ProductService {
  rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse);
  rpc GetProduct(GetProductRequest) returns (GetProductResponse);
  rpc ListProducts(ListProductsRequest) returns (ListProductsResponse);
}

message CreateProductRequest {
  reserved 4;
  string name = 1;
  string description = 2;
  double price = 3;
  string sku = 5;
  string category = 6;
  string currency = 7;
}

message CreateProductResponse {
  string id = 1;
}

message GetProductRequest {
  string id = 1;
}

message GetProductResponse {
  reserved 5;
  string id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
  string sku = 6;
  string category = 7;
  string currency = 8;
  bool active = 9;
}

message ListProductsRequest {}

message ListProductsResponse {
  repeated Product products = 1;
}

message Product {
  reserved 5;
  string id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
  string sku = 6;
  string category = 7;
  string currency = 8;
  bool active = 9;
}
