CREATE TABLE IF NOT EXISTS billing_orders (
 order_id VARCHAR(128) PRIMARY KEY, user_id VARCHAR(128) NULL, currency CHAR(3) NOT NULL,
 total_minor BIGINT NOT NULL, paid BOOLEAN NOT NULL DEFAULT FALSE, fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
 invoice_id CHAR(36) NULL, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS invoices (
 id CHAR(36) PRIMARY KEY, invoice_number VARCHAR(40) NOT NULL UNIQUE, order_id VARCHAR(128) NOT NULL UNIQUE,
 user_id VARCHAR(128) NULL, currency CHAR(3) NOT NULL, subtotal_minor BIGINT NOT NULL, tax_minor BIGINT NOT NULL DEFAULT 0,
 total_minor BIGINT NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'draft', issued_at TIMESTAMP(6) NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS invoice_lines (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id CHAR(36) NOT NULL, description VARCHAR(320) NOT NULL,
 quantity INT UNSIGNED NOT NULL, unit_price_minor BIGINT NOT NULL, tax_rate_bps INT UNSIGNED NOT NULL DEFAULT 0, tax_minor BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT fk_invoice_line_invoice FOREIGN KEY(invoice_id) REFERENCES invoices(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS credit_notes (
 id CHAR(36) PRIMARY KEY, credit_note_number VARCHAR(40) NOT NULL UNIQUE, invoice_id CHAR(36) NOT NULL,
 amount_minor BIGINT NOT NULL, reason VARCHAR(500) NOT NULL, issued_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 CONSTRAINT fk_credit_invoice FOREIGN KEY(invoice_id) REFERENCES invoices(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS accounting_exports (
 id CHAR(36) PRIMARY KEY, format VARCHAR(20) NOT NULL, status VARCHAR(24) NOT NULL,
 row_count INT UNSIGNED NOT NULL DEFAULT 0, content LONGTEXT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
